### ISSUE TITLE
Doesn't work with ? for parameters.

### ISSUE THREAD

**Issue by william44isme** [ripper234/Whatever-Origin#10]
The URL scheme forces you to use ampersands after the first ? for parameters. This means you can't currently use Whatever Origin to get a website which uses parameters as you are forced to start the parameters in the requested website's URL with an ampersand which doesn't work, as a question mark is used at the beginning.

**Comment by mbacklas** [comment]
I got around this like so:
```
$.getJSON('http://whateverorigin.org/get?url=' + encodeURIComponent('http://www.example.com/xml_to_json.php/?product=') + prod_id +  '&callback=?', function(data){ // stuff here });
```

Notice the forward slash before the query, you have to escape it first.

**Comment by x43x61x69** [comment]
This problem still exists. :(

**Comment by macdonjo** [comment]
My attempt at fixing this is in pull request 22.

**Comment by ripper234** [comment]
Merged fix & deployed to Heroku.
Plus, updated Heroku stack to cedar-14, it was using an outdated and broken cedar-10 stack.
