### ISSUE TITLE
Service is down?

### ISSUE THREAD

**Issue by sergiotapia** [ripper234/Whatever-Origin#13]
I always get a 503 since about yesterday, any idea why?

For example:

```
$.getJSON('http://whateverorigin.org/get?url=' + encodeURIComponent('http://google.com') + '&callback=?', function(data){
    alert(data.contents);
});
```

```
Remote Address:23.23.143.170:80
Request URL:http://www.whateverorigin.org/get?url=http%3A%2F%2Fwhateverorigin.org&callback=jQuery1110046431685192510486_1415892161471&_=1415892161472
Request Method:GET
Status Code:503 Service Unavailable
```

**Comment by 175451** [comment]
It's happening again, maybe another restard would help? Thx

**Comment by ripper234** [comment]
It seems to be working now (homepage at least).

On Tue, Jan 5, 2016 at 6:08 PM, 175451 <notifications@github.com> wrote:

> It's happening again, maybe another restard would help? Thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ripper234/Whatever-Origin/issues/13#issuecomment-169045747>
> .
>



-- 
Ron Gross
Skype = ripper234, Schedule my time - meetme.so/RonGross
CNO <http://www.chiefninjaofficer.com/>
