### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by eternal-sorrow** [ripper234/Whatever-Origin#19]
when i try the example fro whateverorigin.org main page? i get the following error in browser console:
``` GET https://whateverorigin.org/get?url=https%3A%2F%2Fgoogle.com&callback=jQuery21302342975828796625_1446012234681&_=1446012234682 net::ERR_CONNECTION_REFUSED```

**Comment by limtaesu** [comment]
in the meantime, checkout limtaesu/alloworigin

**Comment by eternal-sorrow** [comment]
@limtaesu thanks
