### ISSUE TITLE
Shutdown notice

### ISSUE THREAD

**Issue by ripper234** [ripper234/Whatever-Origin#30]
**<s>!!! The live website for this project will SHUT DOWN on June 1st 2021 due to lack of maintainers !!!**
**You are welcome to fork it or join this project as a maintainer.</s>**

As there is demand from the public - *the service will continue at this address at least until 2022*.

**[This project is not maintained](https://github.com/ripper234/Whatever-Origin/issues/12)**. Please also checkout [alloworigin](https://github.com/Eiledon/alloworigin), written in Django.

**Comment by markrosenbaum** [comment]
Hi, I am willing to fully host the code and domain for your project, It can be either somesubdomain.cyberwolf.tech or somesubdomain.cyberwolf.dev.  It would be easier to do it on cyberwolf.tech though.  I will use an always on repl on repl.it.

**Comment by markrosenbaum** [comment]
Just reply if your interested.

**Comment by ajaypillay** [comment]
Hi, given that it's a month to the service being shut down, I was curious if there has been/will be any handover.

I've not been able to find any alternative to this, seems like every other iteration of this is no longer maintained/shut down too.
[Any Origin](anyorigin.com), [All Origins](http://multiverso.me/AllOrigins/), [crossorigin](https://crossorigin.me/) and even the suggestion in the README, [alloworigin](alloworigin.com) are all not operational.

**Comment by markrosenbaum** [comment]
I am yet to receive any reply from the owner so i'm not sure.  I had the same problem which is why I offered my domain for use.

**Comment by ajaypillay** [comment]
Yeah I'm currently exploring hosting [cors anywhere](https://github.com/Rob--W/cors-anywhere) (as per [this guide](https://dev.to/imiebogodson/fixing-the-cors-error-by-hosting-your-own-proxy-on-heroku-3lcb)) on Heroku just so I still have something to rely on.

I do definitely think that whatever origin as a public facing solution to sidestepping CORS is still extremely useful and it does have its place. Hope this can be continued!

**Comment by markrosenbaum** [comment]
yeah, if you do get it setup tell me. I can be emailed at pi@cyberwolf.tech

**Comment by ripper234** [comment]
Hi guys, apologies, I've been away from my inbox in the last month.
I wasn't aware the alternatives were not active.

As there is demand from the public - *the service will continue at this address at least until 2022*.

This service runs on Heroku free tier and costs me no money.
What I'm looking for is some involvement from the community in maintain the code & infra.
I'm no longer maintain this at any level for years...

If someone wants to setup an alternative server somewhere, I can update the DNS to their server. I just want there to be someone to respond to issues opened by the community.

**Comment by linden** [comment]
I've taken over maintaining this project and [we're transitioning to a new backend](https://github.com/ripper234/Whatever-Origin#transitioning-the-live-site). 🎉

**Comment by reynaldichernando** [comment]
Apologies for necroing this issue, but I can't seem to find any code for the Go rewrite by @linden. Is it still accessible?

I can see that the site and the proxy is running, but seems like the Java version is not the one being used. 

For example, this message doesn't appear on the actual site:
https://github.com/ripper234/Whatever-Origin/blob/6c272d1b8e80d0710def7100590836f3f5711f4b/app/views/main.html#L25

**Comment by ajaypillay** [comment]
@reynaldichernando Could this be it? https://github.com/linden/whatever

**Comment by reynaldichernando** [comment]
Ah, you're right, I missed that, it's in their pinned repository. That one seems to be more stable compared to whateverorigin.org. I get intermittent Heroku errors when using the main proxy. I suspect it has to do with the DNS configuration.
